numero1 = input()
numero2 = input()
soma = float(numero1) + float(numero2)
subtracao = float(numero1) - float(numero2)
multiplicacao = float(numero1) * float(numero2)
divisao = float(numero1) / float(numero2)
print('%.2f' % soma)
print('%.2f' % subtracao)
print('%.2f' % multiplicacao)
print('%.2f' % divisao)
